project:
  type: website
  render:
    - "*.qmd"
    - "!posts/2024-05-14-quarto-to-confluence/quarto-example*/"

website:
  title: "RSE Tools"
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/NBISweden/Training-Tech-shorts
  repo-actions: [edit, source, issue]
  navbar:
    search: true
    left:
      - schedule.qmd
      - contributing.qmd
      - cheatsheets.qmd
    right:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/NBISweden/Training-Tech-shorts
          - text: Report an issue
            href: https://github.com/NBISweden/Training-Tech-shorts/issues
          - text: Suggest a walkthrough
            href: https://github.com/NBISweden/Training-Tech-shorts/issues
          - text: Discuss a post
            href: https://github.com/NBISweden/Training-Tech-shorts/discussions
format:
  html:
    theme:
      - minty

code-annotations: hover
