project:
  type: book

book:
  title: "Training: Tech shorts"
  author: "NBIS"
  date: last-modified
  page-navigation: true
  sidebar:
    title: "Content:"
    search: true
  chapters:
    - index.qmd
    - schedule.qmd
    - part: "Git"
      chapters:
        - git/git-intro.qmd
    - part: "Github"
      chapters:
        - github/gh-collaboration.qmd
    - part: "Pixi"
      chapters:
        - pixi/pixi-intro.qmd
    - part: "Apptainer"
      chapters:
        - apptainer/apptainer-intro.qmd
    - part: "Gitpod"
      chapters:
        - gitpod/gitpod-intro.qmd
    - part: "Quarto"
      chapters:
        - quarto/quarto-intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: minty



